var app = angular.module("harrisonApp", []);

app.controller("harrison", function($scope) {
    $scope.results = 
    [
        { age: 0, description: "Urodził się w Chicago"},
        { age: 1, description: "Dorastał na przedmieściach Chicago"},
        { age: 2, description: "Dorastał na przedmieściach Chicago"},
        { age: 3, description: "Urodził się jego brat Terence"},
        { age: 4, description: "Dorastał na przedmieściach Chicago"},
        { age: 5, description: "Dorastał na przedmieściach Chicago"},
        { age: 6, description: "Dorastał na przedmieściach Chicago"},
        { age: 7, description: "Dorastał na przedmieściach Chicago"},
        { age: 8, description: "Dorastał na przedmieściach Chicago"},
        { age: 9, description: "Dorastał na przedmieściach Chicago"},
        { age: 10, description: "Dorastał na przedmieściach Chicago"},
        { age: 11, description: "Dorastał na przedmieściach Chicago"},
        { age: 12, description: "Dorastał na przedmieściach Chicago"},
        { age: 13, description: "Aktywnie działał w harcerstwie"},
        { age: 14, description: "Aktywnie działał w harcerstwie"},
        { age: 15, description: "Aktywnie działał w harcerstwie"},
        { age: 16, description: "Pracował w szkolnej rozgłośni jako spiker"},
        { age: 17, description: "Pracował w szkolnej rozgłośni jako spiker"},
        { age: 18, description: "Ukończył Maine East High School w Park Ridge"},
        { age: 19, description: "Studiował filozofię i anglistykę w Ripon College (Wisconsin)"},
        { age: 20, description: "Należał do bractwa Sigma Nu w Ripon College"},
        { age: 21, description: "Uczęszczał na zajęcia teatralne w Ripon College"},
        { age: 22, description: "Rzucił szkołę i wyjechał do Los Angeles"},
        { age: 23, description: "Podpisał kontrakt z Columbia Pictures"},
        { age: 24, description: "Zadebiutował w filmie Spryciarz Ed"},
        { age: 25, description: "Po raz pierwszy został ojcem. Zagrał ponadto w filmie Czas zabijania"},
        { age: 26, description: "Zagrał w filmie Journey to Shiloh"},
        { age: 27, description: "Dorabiał jako stolarz"},
        { age: 28, description: "Zagrał w filmie uciekający punkt"},
        { age: 29, description: "Dorabiał jako stolarz"},
        { age: 30, description: "Zagrał w filmie Amerykańskie graffiti"},
        { age: 31, description: "Zagrał w filmie Rozmowa"},
        { age: 32, description: "Zagrał w filmie Judgment: The Court Martial of Lieutenant William Calley"},
        { age: 33, description: "Zagrał w filmie Dynastia"},
        { age: 34, description: "Zagrał w filmie Gwiezdne wojny: część IV – Nowa nadzieja"},
        { age: 35, description: "Został nominowany do Saturna w kategorii najlepszy aktor (Gwiezdne wojny: część IV – Nowa nadzieja)"},
        { age: 36, description: "Zagrał w filmie Komandosi z Navarony"},
        { age: 37, description: "Zagrał w filmie Czas apokalipsy"},
        { age: 38, description: "Zagrał w filmie Gwiezdne wojny: część V – Imperium kontratakuje"},
        { age: 39, description: "Otrzymał Saturna dla najlepszego aktora (Poszukiwacze zaginionej arki)"},
        { age: 40, description: "Zagrał w filmie Łowca androidów"},
        { age: 41, description: "Zagrał w filmie Gwiezdne wojny: część VI – Powrót Jedi"},
        { age: 42, description: "Został nominowany do nagrody Saturna w kategorii najlepszy aktor (Indiana Jones i Świątynia Zagłady)"},
        { age: 43, description: "Za rolę w filmie Świadek otrzymał nominację do nagrody BAFTA i Złotego Globu w kategorii najlepszy aktor"},
        { age: 44, description: "Został nominowany do Oscara (Świadek) oraz Złotego Globu (Wybrzeże Moskitów) w kategorii najlepszy aktor"},
        { age: 45, description: "Urodził mu się pierwszy syn Benjamin"},
        { age: 46, description: "Zagrał w filmach Frantic oraz Pracująca dziewczyna"},
        { age: 47, description: "Został nominowany do nagrody Saturna w kategorii najlepszy aktor (Indiana Jones i ostatnia krucjata)"},
        { age: 48, description: "Zagrał w filmie Uznany za niewinnego"},
        { age: 49, description: "Odrzucił rolę w filmie JFK, która ostatecznie trafiła do Kevina Costnera"},
        { age: 50, description: "Zagrał w filmie Czas patriotów"},
        { age: 51, description: "Został nominowany do Złotego Globu w kategorii najlepszy aktor (Ścigany)"},
        { age: 52, description: "Zagrał w filmie Stan zagrożenia"},
        { age: 53, description: "Został nominowany do Złotego Globu w kategorii najlepszy aktor (Sabrina)"},
        { age: 54, description: "Zajął 1. miejsce w rankingu magazynu Empire na 100 największych gwiazd filmowych wszech czasów"},
        { age: 55, description: "Zagrał w filmach Air Force One oraz Zdrada"},
        { age: 56, description: "Otrzymał People’s Choice Award za rolę w filmie Sześć dni, siedem nocy"},
        { age: 57, description: "Otrzymał People’s Choice Award za rolę w filmie Zagubione serca"},
        { age: 58, description: "Został nagrodzony przez American Film Institute za całokształt twórczości"},
        { age: 59, description: "Występował w reklamie samochodów marki Lancia"},
        { age: 60, description: "Otrzymał Złoty Glob za całokształt twórczości"},
        { age: 61, description: "Otrzymał własną gwiazdę na Hollywoodzkiej Alei Sław"},
        { age: 62, description: "Został wybrany przewodniczącym Young Eagles Chapter w Stowarzyszeniu Lotnictwa Eksperymentalnego"},
        { age: 63, description: "Spędzał wolne chwile jako pilot samolotu"},
        { age: 64, description: "Przyznano mu nagrodę Jules Verne Spirit of Nature Award za pracę na rzecz ochrony przyrody"},
        { age: 65, description: "Został uznany przez magazyn People za najseksowniejszego żyjącego mężczyznę"},
        { age: 66, description: "Został nominowany do nagrody Saturna oraz People’s Choice Award w kategorii najlepszy aktor (Indiana Jones i Królestwo Kryształowej Czaszki)"},
        { age: 67, description: "Zagrał w filmie Ścigani"},
        { age: 68, description: "Ożenił się po raz trzeci. Zagrał ponadto w filmie Środki nadzwyczajne"},
        { age: 69, description: "Zagrał w filmie Kowboje i obcy"},
        { age: 70, description: "Został nominowany do Saturna za rolę w filmie Gra Endera"},
        { age: 71, description: "Zagrał w filmach 42 – Prawdziwa historia amerykańskiej legendy oraz Paranoja"},
        { age: 72, description: "Zagrał w filmie Niezniszczalni 3"},
        { age: 73, description: "Zagrał w filmach  Gwiezdne wojny: Przebudzenie Mocy oraz Wiek Adelaine"},
        { age: 74, description: "Otrzymał Saturna za rolę w filmie Gwiezdne wojny: Przebudzenie mocy"},
        { age: 75, description: "Zagra w filmie Blade Runner 2049"},
        { age: 76, description: "Pojawi się w filmie You Belong to Me"},
        { age: 77, description: "Nadal będzie najlepszy"},
        { age: 78, description: "Pojawi się w filmie Indiana Jones 5"},
        { age: 79, description: "Nadal będzie najlepszy"},
        { age: 80, description: "Nadal będzie najlepszy"},
        { age: 81, description: "Nadal będzie najlepszy"},
        { age: 82, description: "Nadal będzie najlepszy"},
        { age: 83, description: "Nadal będzie najlepszy"},
        { age: 84, description: "Nadal będzie najlepszy"},
        { age: 85, description: "Nadal będzie najlepszy"},
        { age: 86, description: "Nadal będzie najlepszy"},
        { age: 87, description: "Nadal będzie najlepszy"},
        { age: 88, description: "Nadal będzie najlepszy"},
        { age: 89, description: "Nadal będzie najlepszy"},
        { age: 90, description: "Nadal będzie najlepszy"},
        { age: 91, description: "Nadal będzie najlepszy"},
        { age: 92, description: "Nadal będzie najlepszy"},
        { age: 93, description: "Nadal będzie najlepszy"},
        { age: 94, description: "Nadal będzie najlepszy"},
        { age: 95, description: "Nadal będzie najlepszy"},
        { age: 96, description: "Nadal będzie najlepszy"},
        { age: 97, description: "Nadal będzie najlepszy"},
        { age: 98, description: "Nadal będzie najlepszy"},
        { age: 99, description: "Nadal będzie najlepszy"},
        { age: 100, description: "Nadal będzie najlepszy"}
    ];
});
